config/routes.rb
  Rails.application.routes.draw do
  resources :structures
  resources :locations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tags
  resources :complaints, :except => [:index, :new]
  get '/complaints/new/:id', to: 'complaints#new', as: :new_complaint
  root 'issue#current_issues'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/current_issues', to: 'issue#current_issues', as: :current_issues
  get '/closed_issues', to: 'issue#closed_issues', as: :closed_issues
end

app/models/complaint.rb
class Complaint < ApplicationRecord
    belongs_to :tag
    belongs_to :location
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  # GET /complaints
  # GET /complaints.json
  def index
    @complaints = Complaint.all
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints
  # POST /complaints.json
  def create
    @complaint = Complaint.new(complaint_params)

    respond_to do |format|
      if @complaint.save
        format.html { redirect_to current_issues_path, notice: 'Complaint was successfully created.' }
        format.json { render :show, status: :created, location: @complaint }
      else
        format.html { render :new }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaints/1
  # PATCH/PUT /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: 'Complaint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complaint_params
      params.require(:complaint).permit(:tag_id, :subject, :description, :status, :user_id)
    end
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/views/complaints/_form.html.erb
<%= form_with(model: complaint, local: true) do |form| %>
  <% if complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
      <% complaint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="hero is-light">
        <div class="hero-body">
        <div class="block">
        <h1>New Complaint</h1>

        </div>
  <div class="column is-4 container">
  <div class="field block select">
    <%= form.collection_select :tag_id, Tag.all, :id, :tag_name, include_blank: 'Select Tag'%>
  </div>

  <div class="field block">
    <%= form.text_field :subject, class: 'input', placeholder: 'Subject' %>
  </div>

  <div class="field block">
    <%= form.text_field :description, class: 'textarea', placeholder: 'Description' %>
  </div>

  <div class="actions">
    <%= form.submit%>
  </div>
  </div>
        </div>
</div>
<% end %>

app/views/complaints/edit.html.erb
<h1>Editing Complaint</h1>

<%= render 'form', complaint: @complaint %>

<%= link_to 'Show', @complaint %> |
<%= link_to 'Back', complaints_path %>

app/views/complaints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Complaints</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>Subject</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td><%= complaint.tag.tag_name %></td>
        <td><%= complaint.subject %></td>
        <td><%= complaint.description %></td>
        <td><%= link_to 'Show', complaint %></td>
        <td><%= link_to 'Edit', edit_complaint_path(complaint) %></td>
        <td><%= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complaint', new_complaint_path %>

app/views/complaints/new.html.erb
<%= render 'form', complaint: @complaint %>

app/views/complaints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @complaint.tag_id %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @complaint.subject %>
</p>

<p>
  <strong>Description:</strong>
  <%= @complaint.description %>
</p>

<%= link_to 'Edit', edit_complaint_path(@complaint) %> |
<%= link_to 'Back', complaints_path %>