config/routes.rb
  Rails.application.routes.draw do
  resources :structures
  resources :locations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tags
  resources :complaints, :except => [:index, :new]
  get '/complaints/new/:id', to: 'complaints#new', as: :new_complaint
  root 'issue#current_issues'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/current_issues', to: 'issue#current_issues', as: :current_issues
  get '/closed_issues', to: 'issue#closed_issues', as: :closed_issues
end

app/views/layouts/_navbar.html.erb
<div class="navbar is-dark">
	
	<div class="navbar-menu">
		<div class="navbar-left">
		<%= link_to 'Issues', current_issues_path, class: "navbar-item" %>
		<% if user_signed_in? %>
		<%= link_to 'Create Tag', new_tag_path, class: "navbar-item" %>
		<%= link_to 'Create Structure', new_structure_path, class: "navbar-item" %>
		<%= link_to 'Create Location', new_location_path, class: "navbar-item" %>
		<% end %>
		</div>
		<div class="navbar-right">
		<% if !user_signed_in? %>
		<%= link_to 'Sign In', new_user_session_path, class: "navbar-item" %>
		<% else %>
		<%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "navbar-item" %>
		<% end %>
		</div>
		
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComplaintPortal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>

    <%= debug(params) if Rails.env.development? %> 
  </body>
</html>